package org.ednovo.gooru.core.cassandra.model;

import javax.persistence.Column;
import javax.persistence.Entity;

@Entity(name = "codeTypeCo")
public class CodeTypeCo {

	@Column
	private Integer typeId;
	
	@Column
	private Integer codeId ;
	
	@Column
	private Short depth;
	
	@Column
	private String label;
	
	@Column
	private Integer isAutogeneratedCode;

	public Integer getCodeId() {
		return codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	public Short getDepth() {
		return depth;
	}

	public void setDepth(Short depth) {
		this.depth = depth;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getIsAutogeneratedCode() {
		return isAutogeneratedCode;
	}

	public void setIsAutogeneratedCode(Integer isAutogeneratedCode) {
		this.isAutogeneratedCode = isAutogeneratedCode;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public Integer getTypeId() {
		return typeId;
	}
}
