package org.ednovo.gooru.core.api.model;

import java.io.Serializable;

public class CodeType extends OrganizationModel implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -3874697285296134853L;


	public static final Integer TAXONOMY = 1;
	public static final Integer GRADE = 2;
	public static final Integer SUBJECT = 3;
	public static final Integer UNIT = 4;
	public static final Integer TOPIC = 5;
	public static final Integer LESSON = 6;
	
	private Integer typeId;
	private Integer codeId ;
	private Short depth;
	private String label;
	private Integer isAutogeneratedCode;
	private Code code;
	
	public Code getCode() {
		return code;
	}
	public void setCode(Code code) {
		this.code = code;
	}

	public String getLabel() {
		return label;
	}
	public void setLabel(String label) {
		this.label = label;
	}
	public Integer getTypeId() {
		return typeId;
	}
	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}
	
	public Integer getCodeId() {
		return codeId;
	}
	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}
	public Short getDepth() {
		return depth;
	}
	public void setDepth(Short depth) {
		this.depth = depth;
	}
	public Integer getIsAutogeneratedCode() {
		return isAutogeneratedCode;
	}
	public void setIsAutogeneratedCode(Integer isAutogeneratedCode) {
		this.isAutogeneratedCode = isAutogeneratedCode;
	}
}
