/*******************************************************************************
 * CodeTypeTransModel.java
 *  gooru-core
 *  Created by Gooru on 2014
 *  Copyright (c) 2014 Gooru. All rights reserved.
 *  http://www.goorulearning.org/
 *       
 *  Permission is hereby granted, free of charge, to any 
 *  person obtaining a copy of this software and associated 
 *  documentation. Any one can use this software without any 
 *  restriction and can use without any limitation rights 
 *  like copy,modify,merge,publish,distribute,sub-license or 
 *  sell copies of the software.
 *  
 *  The seller can sell based on the following conditions:
 *  
 *  The above copyright notice and this permission notice shall be   
 *  included in all copies or substantial portions of the Software. 
 * 
 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY    
 *   KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE  
 *   WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR   
 *   PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE       AUTHORS 
 *   OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR 
 *   OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT 
 *   OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
 *   WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN 
 *   THE SOFTWARE.
 ******************************************************************************/
package org.ednovo.gooru.core.api.model;

import java.io.Serializable;

import org.ednovo.gooru.core.api.model.Code;

public class CodeTypeTransModel implements Serializable {

		/**
	 * 
	 */
	private static final long serialVersionUID = -3933857500563245976L;
	
	
		public static final Integer TAXONOMY = 1;
		public static final Integer GRADE = 2;
		public static final Integer SUBJECT = 3;
		public static final Integer UNIT = 4;
		public static final Integer TOPIC = 5;
		public static final Integer LESSON = 6;
		
		private Integer typeId;
		private Integer codeId ;
		private Short depth;
		private String label;
		private Integer isAutogeneratedCode;
		private Code code;
		
		public Code getCode() {
			return code;
		}
		public void setCode(Code code) {
			this.code = code;
		}

		public String getLabel() {
			return label;
		}
		public void setLabel(String label) {
			this.label = label;
		}
		public Integer getTypeId() {
			return typeId;
		}
		public void setTypeId(Integer typeId) {
			this.typeId = typeId;
		}
		
		public Integer getCodeId() {
			return codeId;
		}
		public void setCodeId(Integer codeId) {
			this.codeId = codeId;
		}
		public Short getDepth() {
			return depth;
		}
		public void setDepth(Short depth) {
			this.depth = depth;
		}
		public Integer getIsAutogeneratedCode() {
			return isAutogeneratedCode;
		}
		public void setIsAutogeneratedCode(Integer isAutogeneratedCode) {
			this.isAutogeneratedCode = isAutogeneratedCode;
		}


	}

